<?php
// export_report.php - Dedicated CSV export handler for library reports
// Include only the database connection, not the header
include('../includes/db.php');

// Check if download parameter exists
if (!isset($_GET['download'])) {
    // Redirect back to reports page if no download parameter
    header('Location: report.php');
    exit;
}

// Helper function to output beautiful CSV with updated date
function output_beautiful_csv($filename, $data, $headers = [], $title = '')
{
    // Set headers for CSV download
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, must-revalidate');
    header('Expires: Sat, 26 Jul 1997 05:00:00 GMT');

    // Create output handle
    $output = fopen('php://output', 'w');

    // Add BOM for proper UTF-8 encoding in Excel
    fputs($output, "\xEF\xBB\xBF");

    // Add title section
    if (!empty($title)) {
        fputcsv($output, [$title]);
        fputcsv($output, ['Generated on: ' . date('Y-m-d H:i:s')]);
        fputcsv($output, ['Generated by: Library Management System']);
        fputcsv($output, ['']); // Empty row for spacing
    }

    // Add headers if provided
    if (!empty($headers)) {
        fputcsv($output, $headers);
    }

    // Add data rows
    foreach ($data as $row) {
        fputcsv($output, $row);
    }

    // Add footer with summary
    fputcsv($output, ['']); // Empty row
    fputcsv($output, ['=== EXPORT SUMMARY ===']);
    fputcsv($output, ['Total Records: ' . count($data)]);
    fputcsv($output, ['Export Date: ' . date('Y-m-d')]);
    fputcsv($output, ['Export Time: ' . date('H:i:s')]);
    fputcsv($output, ['Timezone: ' . date_default_timezone_get()]);

    fclose($output);
    exit;
}

// Handle different download types
switch ($_GET['download']) {
    case 'all_books':
        $query = "SELECT title, author, genre, serialno, pages, created_at FROM books ORDER BY created_at DESC";
        $result = $conn->query($query);
        
        if ($result && $result->num_rows > 0) {
            $rows = [];
            while ($row = $result->fetch_assoc()) {
                $rows[] = [
                    $row['title'],
                    $row['author'],
                    $row['genre'],
                    $row['serialno'],
                    $row['pages'],
                    date('Y-m-d H:i:s', strtotime($row['created_at']))
                ];
            }
            
            output_beautiful_csv(
                'Library_All_Books_' . date('Y-m-d_H-i-s') . '.csv',
                $rows,
                ['Title', 'Author', 'Genre', 'Serial No', 'Pages', 'Created At'],
                'LIBRARY MANAGEMENT SYSTEM - ALL BOOKS REPORT'
            );
        } else {
            // No data found, create empty report
            output_beautiful_csv(
                'Library_All_Books_' . date('Y-m-d_H-i-s') . '.csv',
                [['No books found in the system']],
                ['Message'],
                'LIBRARY MANAGEMENT SYSTEM - ALL BOOKS REPORT (EMPTY)'
            );
        }
        break;

    case 'reserved_books':
        $query = "
            SELECT b.title, b.author, b.serialno, b.genre, 
                   COALESCE(r.name, 'Unknown') AS reserved_by, 
                   r.reservation_date, r.status, r.due_date,
                   DATEDIFF(CURDATE(), r.due_date) as days_overdue
            FROM reservations r
            JOIN books b ON r.book_id = b.id
            WHERE r.status = 'reserved'
            ORDER BY r.reservation_date DESC
        ";
        $result = $conn->query($query);
        
        if ($result && $result->num_rows > 0) {
            $rows = [];
            while ($row = $result->fetch_assoc()) {
                $overdue_status = '';
                if ($row['days_overdue'] > 0) {
                    $overdue_status = 'OVERDUE (' . $row['days_overdue'] . ' days)';
                } elseif ($row['days_overdue'] == 0) {
                    $overdue_status = 'DUE TODAY';
                } else {
                    $overdue_status = 'Active';
                }
                
                $rows[] = [
                    $row['title'],
                    $row['author'],
                    $row['serialno'],
                    $row['genre'],
                    $row['reserved_by'],
                    date('Y-m-d H:i:s', strtotime($row['reservation_date'])),
                    $row['due_date'] ? date('Y-m-d', strtotime($row['due_date'])) : 'Not Set',
                    strtoupper($row['status']),
                    $overdue_status
                ];
            }
            
            output_beautiful_csv(
                'Library_Reserved_Books_' . date('Y-m-d_H-i-s') . '.csv',
                $rows,
                ['Title', 'Author', 'Serial No', 'Genre', 'Reserved By', 'Reserved At', 'Due Date', 'Status', 'Overdue Status'],
                'LIBRARY MANAGEMENT SYSTEM - RESERVED BOOKS REPORT'
            );
        } else {
            output_beautiful_csv(
                'Library_Reserved_Books_' . date('Y-m-d_H-i-s') . '.csv',
                [['No reserved books found']],
                ['Message'],
                'LIBRARY MANAGEMENT SYSTEM - RESERVED BOOKS REPORT (EMPTY)'
            );
        }
        break;

    case 'employees':
        $query = "SELECT full_name, username, email, address, dzongkhag, phone_no, dob, created_at 
                  FROM employee_data ORDER BY created_at DESC";
        $result = $conn->query($query);
        
        if ($result && $result->num_rows > 0) {
            $rows = [];
            while ($row = $result->fetch_assoc()) {
                $rows[] = [
                    $row['full_name'],
                    $row['username'],
                    $row['email'],
                    $row['address'],
                    $row['dzongkhag'],
                    $row['phone_no'],
                    $row['dob'] ? date('Y-m-d', strtotime($row['dob'])) : 'Not Provided',
                    date('Y-m-d H:i:s', strtotime($row['created_at']))
                ];
            }
            
            output_beautiful_csv(
                'Library_Employees_' . date('Y-m-d_H-i-s') . '.csv',
                $rows,
                ['Full Name', 'Username', 'Email', 'Address', 'Dzongkhag', 'Phone No', 'Date of Birth', 'Created At'],
                'LIBRARY MANAGEMENT SYSTEM - EMPLOYEE RECORDS REPORT'
            );
        } else {
            output_beautiful_csv(
                'Library_Employees_' . date('Y-m-d_H-i-s') . '.csv',
                [['No employee records found']],
                ['Message'],
                'LIBRARY MANAGEMENT SYSTEM - EMPLOYEE RECORDS REPORT (EMPTY)'
            );
        }
        break;

    case 'feedback':
        $query = "
            SELECT f.id, 
                   COALESCE(u.name, 'Anonymous') as username,
                   f.category, 
                   f.subject, 
                   f.message, 
                   f.rating, 
                   f.priority, 
                   f.created_at,
                   CASE 
                       WHEN f.rating >= 4 THEN 'Positive'
                       WHEN f.rating >= 3 THEN 'Neutral' 
                       WHEN f.rating >= 1 THEN 'Negative'
                       ELSE 'No Rating'
                   END as rating_category
            FROM feedback f
            LEFT JOIN users u ON f.user_id = u.id
            ORDER BY f.created_at DESC
        ";
        $result = $conn->query($query);
        
        if ($result && $result->num_rows > 0) {
            $rows = [];
            while ($row = $result->fetch_assoc()) {
                $rows[] = [
                    $row['id'],
                    $row['username'],
                    $row['category'],
                    $row['subject'] ?: 'No Subject',
                    $row['message'],
                    $row['rating'] ?: 'No Rating',
                    $row['rating_category'],
                    strtoupper($row['priority'] ?: 'medium'),
                    date('Y-m-d H:i:s', strtotime($row['created_at']))
                ];
            }
            
            output_beautiful_csv(
                'Library_Feedback_' . date('Y-m-d_H-i-s') . '.csv',
                $rows,
                ['ID', 'Username', 'Category', 'Subject', 'Message', 'Rating', 'Rating Category', 'Priority', 'Submitted At'],
                'LIBRARY MANAGEMENT SYSTEM - FEEDBACK REPORT'
            );
        } else {
            output_beautiful_csv(
                'Library_Feedback_' . date('Y-m-d_H-i-s') . '.csv',
                [['No feedback entries found']],
                ['Message'],
                'LIBRARY MANAGEMENT SYSTEM - FEEDBACK REPORT (EMPTY)'
            );
        }
        break;

    case 'summary':
        // Generate a comprehensive summary report
        $reports = [];
        
        // Get book statistics
        $bookStats = $conn->query("
            SELECT 
                COUNT(*) as total_books,
                COUNT(DISTINCT author) as unique_authors,
                COUNT(DISTINCT genre) as unique_genres,
                AVG(pages) as avg_pages
            FROM books
        ");
        $bookData = $bookStats->fetch_assoc();
        
        // Get reservation statistics
        $reservationStats = $conn->query("
            SELECT 
                COUNT(*) as total_reservations,
                SUM(CASE WHEN status = 'reserved' THEN 1 ELSE 0 END) as active_reservations,
                SUM(CASE WHEN status = 'returned' THEN 1 ELSE 0 END) as returned_books,
                SUM(CASE WHEN status = 'cancelled' THEN 1 ELSE 0 END) as cancelled_reservations
            FROM reservations
        ");
        $reservationData = $reservationStats->fetch_assoc();
        
        // Get feedback statistics
        $feedbackStats = $conn->query("
            SELECT 
                COUNT(*) as total_feedback,
                AVG(rating) as avg_rating,
                COUNT(CASE WHEN priority = 'high' THEN 1 END) as high_priority,
                COUNT(CASE WHEN priority = 'medium' THEN 1 END) as medium_priority,
                COUNT(CASE WHEN priority = 'low' THEN 1 END) as low_priority
            FROM feedback WHERE rating IS NOT NULL
        ");
        $feedbackData = $feedbackStats->fetch_assoc();
        
        // Employee statistics
        $employeeStats = $conn->query("SELECT COUNT(*) as total_employees FROM employee_data");
        $employeeData = $employeeStats->fetch_assoc();
        
        $summaryData = [
            ['LIBRARY STATISTICS SUMMARY', ''],
            ['', ''],
            ['=== BOOK COLLECTION ===', ''],
            ['Total Books', $bookData['total_books'] ?: 0],
            ['Unique Authors', $bookData['unique_authors'] ?: 0],
            ['Unique Genres', $bookData['unique_genres'] ?: 0],
            ['Average Pages per Book', round($bookData['avg_pages'] ?: 0, 2)],
            ['', ''],
            ['=== RESERVATIONS ===', ''],
            ['Total Reservations', $reservationData['total_reservations'] ?: 0],
            ['Active Reservations', $reservationData['active_reservations'] ?: 0],
            ['Returned Books', $reservationData['returned_books'] ?: 0],
            ['Cancelled Reservations', $reservationData['cancelled_reservations'] ?: 0],
            ['', ''],
            ['=== FEEDBACK ===', ''],
            ['Total Feedback Entries', $feedbackData['total_feedback'] ?: 0],
            ['Average Rating', round($feedbackData['avg_rating'] ?: 0, 2)],
            ['High Priority Issues', $feedbackData['high_priority'] ?: 0],
            ['Medium Priority Issues', $feedbackData['medium_priority'] ?: 0],
            ['Low Priority Issues', $feedbackData['low_priority'] ?: 0],
            ['', ''],
            ['=== STAFF ===', ''],
            ['Total Employees', $employeeData['total_employees'] ?: 0],
        ];
        
        output_beautiful_csv(
            'Library_Summary_Report_' . date('Y-m-d_H-i-s') . '.csv',
            $summaryData,
            ['Metric', 'Value'],
            'LIBRARY MANAGEMENT SYSTEM - COMPREHENSIVE SUMMARY REPORT'
        );
        break;

    default:
        // Invalid download type, redirect back
        header('Location: report.php?error=invalid_export_type');
        exit;
}

// If we get here, something went wrong
$conn->close();
header('Location: report.php?error=export_failed');
exit;
?>